"""Adapt validated competition inputs into legacy UrbanHeatOpt files."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import geopandas as gpd
import numpy as np
import pandas as pd

from urbanheatopt.model.costing.annualized import annualize_capex
from urbanheatopt.data.validation.inputs import CaseInputs, validate_case_inputs


@dataclass(frozen=True)
class LegacyAdaptationResult:
    """Paths generated by the legacy adapter."""

    output_dir: Path
    building_ts_csv: Path
    building_data_geojson: Path
    timestamp_hour_map_csv: Path
    heat_generation_units_xlsx: Path
    parameter_costs_xlsx: Path
    waste_heat_profiles_xlsx: Path


def _derive_building_data(inputs: CaseInputs) -> gpd.GeoDataFrame:
    load_stats = (
        inputs.loads.groupby("building_id", sort=False)["heating_kW"]
        .agg(MaxDemand="max", modelled_period_energy_kWh="sum")
        .reset_index()
    )
    buildings = inputs.buildings.merge(load_stats, on="building_id", how="left", validate="one_to_one")
    if buildings[["MaxDemand", "modelled_period_energy_kWh"]].isna().any().any():
        raise ValueError("建筑负荷统计缺失；请先通过 validate_case_inputs")

    adapted = buildings.copy()
    adapted["heated_area"] = adapted["heated_area_m2"].astype("float64")
    adapted["YearlyDemand"] = adapted["modelled_period_energy_kWh"].astype("float64")
    adapted["LocalHeatProdCosts"] = 0.0
    adapted["YearlyHeatingCosts"] = 0.0
    adapted["number_of_dwellings"] = 0
    adapted["GeneralisedThermCap"] = adapted["heated_area"].astype("float64").clip(lower=1.0)
    adapted["GeneralisedThermCond"] = adapted["MaxDemand"].astype("float64").div(25.0).clip(lower=0.01)
    adapted["use_type"] = adapted["use_type"].astype(str)
    adapted["archetype_id"] = adapted["archetype_id"].astype(str)
    return gpd.GeoDataFrame(adapted, geometry="geometry", crs=inputs.buildings.crs)


def _write_heat_generation_units(inputs: CaseInputs, output_dir: Path) -> Path:
    enabled = set(inputs.config["enabled_technology_ids"])
    enabled_tech = inputs.technologies[inputs.technologies["technology_id"].isin(enabled)].copy()
    if enabled_tech.empty:
        raise ValueError("没有启用技术，无法生成 legacy 热源表")

    centroid = inputs.buildings.to_crs(inputs.config["crs"]["projected"]).union_all().centroid
    point = gpd.GeoSeries([centroid], crs=inputs.config["crs"]["projected"]).to_crs(inputs.config["crs"]["input"]).iloc[0]
    rows: list[dict[str, object]] = [
        {
            "unit": "unit row",
            "lat": "deg",
            "lon": "deg",
            "isWH": "-",
            "isBoiler": "-",
            "isTES": "-",
            "O&M and Fuel Costs": "CNY/kWh_th",
            "Power Investment Costs": "CNY/kW_th",
            "Storage Investment Costs": "CNY/kWh_th",
            "Storage loss rate %/h": "%/h",
        }
    ]
    discount_rate = float(inputs.config.get("planning", {}).get("discount_rate", 0.0))
    for index, row in enumerate(enabled_tech.itertuples(index=False), start=1):
        capex_basis = str(getattr(row, "capex_basis", "one_time_capex"))
        annualized_power_cost = annualize_capex(
            capex=float(row.capex_CNY_per_kW),
            discount_rate=discount_rate,
            lifetime_years=float(row.lifetime_years),
            capex_basis=capex_basis,
        )
        rows.append(
            {
                "unit": f"unit_{index}_{row.technology_id}",
                "lat": point.y,
                "lon": point.x,
                "isWH": 0,
                "isBoiler": 1,
                "isTES": 0,
                "O&M and Fuel Costs": float(row.variable_om_CNY_per_kWh_heat),
                "Power Investment Costs": annualized_power_cost,
                "Storage Investment Costs": 0,
                "Storage loss rate %/h": 0,
            }
        )
    path = output_dir / "input_HeatGenerationUnits.xlsx"
    pd.DataFrame(rows).to_excel(path, index=False)
    return path


def _write_parameter_costs(inputs: CaseInputs, output_dir: Path) -> Path:
    cluster_count = int(inputs.config["clustering"]["cluster_count"])
    parameter_costs = pd.DataFrame(
        [
            ("pCostHNS", 1_000_000.0),
            ("pCostPumping", 1e-6),
            ("pTsupply", float(inputs.config["network"]["supply_temperature_C"])),
            ("pTreturn", float(inputs.config["network"]["return_temperature_C"])),
            ("pPipeCostIni", 0.0),
            ("pMassFlowIni", 0.8),
            ("pPipeCostsSlope", 0.0),
            ("param_cluster_size", cluster_count),
            ("cost_DH_connect_building", 0.0),
            ("cost_DH_connect_area", 0.0),
            ("cost_DH_connect_power", 0.0),
            ("daily_hot_water_demand", 0.0),
            ("include_dhw", 0),
            ("allow_double_heating", 0),
            ("phWeight", 1.0),
        ],
        columns=["Parameter", "Value"],
    )
    path = output_dir / "input_ParameterCosts.xlsx"
    parameter_costs.to_excel(path, index=False)
    return path


def _write_empty_waste_heat(inputs: CaseInputs, output_dir: Path) -> Path:
    waste_heat = pd.DataFrame({"time": np.arange(1, len(inputs.timestamp_hour_map) + 1, dtype=int)})
    waste_heat = pd.concat([pd.DataFrame({"time": ["h"]}), waste_heat], ignore_index=True)
    path = output_dir / "input_WastHeatProfiles.xlsx"
    waste_heat.to_excel(path, index=False)
    return path


def adapt_case_to_legacy(case_dir: str | Path, output_dir: str | Path) -> LegacyAdaptationResult:
    """Validate a competition case and write legacy UrbanHeatOpt-compatible files."""

    inputs = validate_case_inputs(case_dir)
    out = Path(output_dir).resolve()
    out.mkdir(parents=True, exist_ok=True)

    building_ts_path = out / "Building_TS.csv"
    inputs.legacy_loads_kW.to_csv(building_ts_path, index=False)

    timestamp_map_path = out / "timestamp_hour_map.csv"
    inputs.timestamp_hour_map.to_csv(timestamp_map_path, index=False)

    building_data_path = out / "Building_Data.geojson"
    _derive_building_data(inputs).to_file(building_data_path, driver="GeoJSON")

    heat_units_path = _write_heat_generation_units(inputs, out)
    parameter_costs_path = _write_parameter_costs(inputs, out)
    waste_heat_path = _write_empty_waste_heat(inputs, out)

    return LegacyAdaptationResult(
        output_dir=out,
        building_ts_csv=building_ts_path,
        building_data_geojson=building_data_path,
        timestamp_hour_map_csv=timestamp_map_path,
        heat_generation_units_xlsx=heat_units_path,
        parameter_costs_xlsx=parameter_costs_path,
        waste_heat_profiles_xlsx=waste_heat_path,
    )


def adapt_case_to_legacy_case_directory(case_dir: str | Path, legacy_root: str | Path | None = None) -> LegacyAdaptationResult:
    """Write validated inputs into the directory layout expected by UrbanHeatOpt."""

    inputs = validate_case_inputs(case_dir)
    root = Path.cwd() if legacy_root is None else Path(legacy_root).resolve()
    case_output = root / inputs.config["case_id"]
    scenario_input = case_output / "scenarios" / inputs.config["scenario_id"] / "input"
    scenario_input.mkdir(parents=True, exist_ok=True)

    result = adapt_case_to_legacy(case_dir, scenario_input)
    building_ts = case_output / "Building_TS.csv"
    building_data = case_output / "Building_Data.geojson"
    timestamp_map = case_output / "timestamp_hour_map.csv"
    result.building_ts_csv.replace(building_ts)
    result.building_data_geojson.replace(building_data)
    result.timestamp_hour_map_csv.replace(timestamp_map)

    return LegacyAdaptationResult(
        output_dir=case_output,
        building_ts_csv=building_ts,
        building_data_geojson=building_data,
        timestamp_hour_map_csv=timestamp_map,
        heat_generation_units_xlsx=result.heat_generation_units_xlsx,
        parameter_costs_xlsx=result.parameter_costs_xlsx,
        waste_heat_profiles_xlsx=result.waste_heat_profiles_xlsx,
    )
